services:
  maru-egg-app:
    container_name: maru-egg-app
    image: ${DOCKER_REPO}
    ports:
      - "8080:8080"
    networks:
      - maru-egg-dev
    volumes:
      - /home/ec2-user/logs:/logs

networks:
  maru-egg-dev: