services:
  maru-egg-app:
    container_name: maru-egg-app
    image: ${DOCKER_REPO}:${IMAGE_TAG}
    ports:
      - "8080:8080"
    networks:
      - maru-egg-dev
    volumes:
      - /home/ec2-user/logs:/logs

  nginx:
    image: nginx:1.27.0
    container_name: maru-egg-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - maru-egg-app
    networks:
      - maru-egg-dev
    command: >
      /bin/sh -c "while true; do sleep 6h && nginx -s reload; done & nginx -g 'daemon off;'"

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c "trap 'exit 0' TERM; while true; do certbot renew; sleep 12h; done"
    networks:
      - maru-egg-dev

networks:
  maru-egg-dev: