version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: maru-egg-local-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Gh852852!
    volumes:
      - maru-egg-db:/var/lib/mysql
volumes:
  maru-egg-local-db: