services:
  maru-egg-app:
    container_name: maru-egg-app
    image: ${DOCKER_REPO}:${IMAGE_TAG}
    ports:
      - "8080:8080"
    networks:
      - maru-egg-dev
    volumes:
      - /home/ec2-user/logs:/logs

  nginx:
    image: nginx:latest
    container_name: maru-egg-nginx
    ports:
      - "80:80"
    networks:
      - maru-egg-dev
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - maru-egg-app

networks:
  maru-egg-dev: