server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /positions.yaml

clients:
  - url: http://{monitooring-ip}:3100/loki/api/v1/push

scrape_configs:
  - job_name: all
    static_configs:
      - targets:
          - localhost
        labels:
          job: all_logs
          __path__: /var/logs/all/*.log

  - job_name: new_qna
    static_configs:
      - targets:
          - localhost
        labels:
          job: new_qna_logs
          __path__: /var/logs/new_qna/*.log

  - job_name: invalid_qna
    static_configs:
      - targets:
          - localhost
        labels:
          job: invalid_qna_logs
          __path__: /var/logs/invalid_qna/*.log

  - job_name: warn
    static_configs:
      - targets:
          - localhost
        labels:
          job: warn_logs
          __path__: /var/logs/warn/*.log

  - job_name: error
    static_configs:
      - targets:
          - localhost
        labels:
          job: error_logs
          __path__: /var/logs/error/*.log