spring:
  application:
    name: MARU_EGG_BE
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:tc:mysql:8.0.26:///testdb
    username: test
    password: test

web-client:
  base-url: ${LLM_BASE_URL}

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace