spring:
  application:
    name: MARU_EGG_BE
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3316/maru-egg-db
    username: root
    password: maruegg!

logging:
  level:
    com:
      zaxxer:
        hikari:
          pool:
            debug
          util:
            trace

    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        orm:
          jpa: debug
        transaction: debug
server:
  port: 8082