spring:
  application:
    name: maru-egg

  profiles:
    active: ${profile}

web-client:
  base-url: ${LLM_BASE_URL}

jwt:
  secretKey: ${JWT_SECRET}

  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: "Authorization"

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: "Authorization-refresh"

springdoc:
  api-docs:
    path: /maru-egg/api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /maru-egg/api-docs.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}