spring:
  profiles:
    active: ${profile}

web-client:
  base-url: ${LLM_BASE_URL}

jwt:
  secretKey: ${JWT_SECRET}

  access:
    expiration: 3600000
    header: "Authorization"

  refresh:
    expiration: 1209600000
    header: "Authorization-refresh"

springdoc:
  api-docs:
    path: /maru-egg/api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /maru-egg/api-docs.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none