services:
  maru-egg-db:
    image: mysql:8.0
    platform: linux/x86_64
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: maruegg!
      MYSQL_DATABASE: maru-egg-db
      MYSQL_USER: maruegg
      MYSQL_PASSWORD: maruegg!
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    command:
      - "--innodb_ft_min_token_size=1"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    ports:
      - 3000:3000
    volumes:
      - ./grafana/volume:/var/lib/grafana
    restart: always
    networks:
      - maru-egg-local

networks:
  maru-egg-local: