services:
  maru-egg-app:
    container_name: maru-egg
    image: ${DOCKER_REPO}:develop-${GITHUB_RUN_NUMBER}
    ports:
      - "8080:8080"
    networks:
      - maru-egg-dev
    volumes:
      - /home/ec2-user/logs:/logs

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus-volume:/prometheus
    ports:
      - '9090:9090'
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: on-failure[:3]
    depends_on:
      - maru-egg-app
    networks:
      - maru-egg-dev
    user: '65534:65534'

networks:
  maru-egg-dev: