services:
  maru-egg-app:
    container_name: maru-egg
    image: ${DOCKER_REPO}:develop-${GITHUB_RUN_NUMBER}
    ports:
      - "8080:8080"
    networks:
      - maru-egg-dev
    volumes:
      - /home/ec2-user/logs:/logs

  nginx:
    depends_on:
      - maru-egg-app
    image: nginx:latest
    container_name: maru-egg-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - maru-egg-dev

  promtail:
    depends_on:
      - maru-egg-app
    container_name: promtail
    image: grafana/promtail:latest
    restart: always
    ports:
      - '9080:9080'
    volumes:
      - ./promtail/config/promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./logs/all:/var/logs/all
      - ./logs/warn:/var/logs/warn
      - ./logs/error:/var/logs/error
      - ./logs/invalid_qna:/var/logs/invalid_qna
      - ./logs/new_qna:/var/logs/new_qna
    command:
      - -config.file=/etc/promtail/promtail-config.yml
    networks:
      - maru-egg-dev

networks:
  maru-egg-dev: