services:
  maru-egg-app:
    container_name: maru-egg
    image: ${DOCKER_REPO}:develop-${GITHUB_RUN_NUMBER}
    ports:
      - "8080:8080"
    networks:
      - maru-egg-dev
    volumes:
      - /home/ec2-user/logs:/logs

  nginx:
    depends_on:
      - maru-egg-app
    image: nginx:latest
    container_name: maru-egg-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - maru-egg-dev

networks:
  maru-egg-dev: