name: MARU EGG CI-CD Workflow

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches:
      - develop

# 권한 설정
permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Java JDK
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # Cache Gradle packages
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # gradle build
      - name: Build with Gradle
        run: ./gradlew build -x test

      # 환경별 yml 파일 생성 - dev
      - name: make application-dev.yml
        if: contains(github.ref, 'develop')
        run: |
          cd ./src/main/resources
          touch ./application-dev.yml
          echo "${{ secrets.YML_DEV }}" > ./application-dev.yml
        shell: bash

      # Check if the JAR file exists
      - name: Check JAR file exists
        run: ls -al build/libs

      # Upload JAR file as artifact
      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: maru-egg-be-jar
          path: build/libs/*.jar

  CD:
    runs-on: ubuntu-latest

    needs: CI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Download JAR file from artifact
      - name: Download JAR file
        uses: actions/download-artifact@v3
        with:
          name: maru-egg-be-jar
          path: build/libs

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Metadata action
      - name: Metadata action
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_REPO }}

      # Build and push Docker image
      - name: Build and push Docker image
        if: contains(github.ref, 'develop')
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}-${{ github.run_number }}
          labels: ${{ steps.meta.outputs.labels }}

      ## deploy to develop
      - name: Set Docker image tag variable
        if: contains(github.ref, 'develop')
        run: echo "IMAGE_TAG=${{ secrets.DOCKER_REPO }}:${{ steps.meta.outputs.tags }}-${{ github.run_number }}" >> $GITHUB_ENV

      - name: Deploy to EC2 dev
        uses: appleboy/ssh-action@master
        if: contains(github.ref, 'develop')
        with:
          host: ${{ secrets.PUBLIC_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PEM_KEY }}
          script: |
            IMAGE_TAG=${{ env.IMAGE_TAG }}
            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            sudo docker pull $IMAGE_TAG
            echo "
            version: '3'
            services:
              db:
                image: mysql:latest
                container_name: maru-egg-db
                ports:
                  - '3306:3306'
                environment:
                  MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
                volumes:
                  - maru-egg-db:/var/lib/mysql

              app:
                image: $IMAGE_TAG
                container_name: maru-egg-app
                ports:
                  - '8080:8080'
                depends_on:
                  - db
                environment:
                  SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/maru_egg
                  SPRING_DATASOURCE_USERNAME: root
                  SPRING_DATASOURCE_PASSWORD: $MYSQL_ROOT_PASSWORD

            volumes:
              maru-egg-db:
            " > docker-compose.yml

            sudo docker-compose down
            sudo docker-compose up -d
            sudo docker rm $(docker ps --filter 'status=exited' -a -q)
            sudo docker image prune -f