name: MARU EGG CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Java JDK
      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Gradle caching
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 환경별 yml 파일 생성
      - name: make application.yml
        if: contains(github.ref, 'main') || contains(github.ref, 'develop')
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.YML }}" > ./src/main/resources/application.yml
        shell: bash

      - name: make application-dev.yml
        if: contains(github.ref, 'develop')
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.YML_DEV }}" > ./src/main/resources/application-dev.yml
        shell: bash

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Check if the JAR file is generated
      - name: Check JAR file exists
        run: ls -al build/libs

      # Get current date
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Metadata action
      - name: Metadata action
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_REPO }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}-${{ steps.date.outputs.date }}
          labels: ${{ steps.meta.outputs.labels }}

      # Deploy
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PUBLIC_DNS }}
          username: ubuntu
          key: ${{ secrets.PEM_KEY }}
          script: |
            touch hello.txt
            echo "hello world" > hello.txt