name: Monitoring CI/CD Workflow

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get GitHub Actions IP Address
        id: get_ip
        run: echo "ip=$(curl -s ifconfig.me)" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-northeast-2'

      - name: Add GitHub Actions IP to Security Group
        env:
          IP: ${{ env.ip }}
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} \
            --protocol tcp --port 22 --cidr ${IP}/32

      - name: Copy docker-compose-monitor.yml into monitor instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.MONITOR_PUBLIC_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PEM_KEY }}
          source: "docker/docker-compose-monitor.yml"
          target: "/home/${{ secrets.USERNAME }}/docker/docker-compose-monitor.yml"
          strip_components: 3
          overwrite: true
          debug: true

      - name: Deploy to EC2 monitor server
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.MONITOR_PUBLIC_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PEM_KEY }}
          script: |
            cd /home/${{ secrets.USERNAME }}
            echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            sudo docker-compose -f docker-compose-monitor.yml up -d
            sudo docker image prune -f

      - name: Remove GitHub Actions IP
        run: |
          aws ec2 revoke-security-group-ingress \
              --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} \
              --protocol tcp --port 22 --cidr "${{ env.ip }}/32"